// <auto-generated />
using System;
using Bookstore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookstore.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501191740_RebuilđB")]
    partial class RebuilđB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bookstore.API.Models.BC_KhachHang", b =>
                {
                    b.Property<int>("MaBaoCaoKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCaoKhachHang"));

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("TongDoanhThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongNo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaBaoCaoKhachHang");

                    b.ToTable("BC_KhachHang");
                });

            modelBuilder.Entity("Bookstore.API.Models.BC_Sach", b =>
                {
                    b.Property<int>("MaBaoCaoSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCaoSach"));

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("TongChiPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongDoanhThu")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaBaoCaoSach");

                    b.ToTable("BC_Sach");
                });

            modelBuilder.Entity("Bookstore.API.Models.CTUD_HoaDon_Giam", b =>
                {
                    b.Property<int>("MaCT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCT"));

                    b.Property<decimal>("GiamToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaUuDai")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("TiLeGiam")
                        .HasColumnType("float");

                    b.HasKey("MaCT");

                    b.HasIndex("MaUuDai");

                    b.ToTable("CTUD_HoaDon_Giam");
                });

            modelBuilder.Entity("Bookstore.API.Models.CTUD_HoaDon_Qua", b =>
                {
                    b.Property<int>("MaCT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCT"));

                    b.Property<int>("MaUuDai")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaCT");

                    b.HasIndex("MaUuDai");

                    b.ToTable("CTUD_HoaDon_Qua");
                });

            modelBuilder.Entity("Bookstore.API.Models.CTUD_Sach_Giam", b =>
                {
                    b.Property<int>("MaCT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCT"));

                    b.Property<decimal>("GiamToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaUuDai")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("TiLeGiam")
                        .HasColumnType("float");

                    b.HasKey("MaCT");

                    b.HasIndex("MaUuDai");

                    b.ToTable("CTUD_Sach_Giam");
                });

            modelBuilder.Entity("Bookstore.API.Models.CTUD_Sach_Qua", b =>
                {
                    b.Property<int>("MaCT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCT"));

                    b.Property<int>("MaUuDai")
                        .HasColumnType("int");

                    b.HasKey("MaCT");

                    b.HasIndex("MaUuDai");

                    b.ToTable("CTUD_Sach_Qua");
                });

            modelBuilder.Entity("Bookstore.API.Models.CT_BC_KhachHang", b =>
                {
                    b.Property<int>("MaBaoCaoKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<decimal>("DaTra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DoanhThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NoCuoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NoDau")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NoPhatSinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoHoaDon")
                        .HasColumnType("int");

                    b.Property<float>("TiLeDoanhThu")
                        .HasColumnType("real");

                    b.HasKey("MaBaoCaoKhachHang", "MaKhachHang");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("CT_BC_KhachHang");
                });

            modelBuilder.Entity("Bookstore.API.Models.CT_BC_Sach", b =>
                {
                    b.Property<int>("MaBaoCaoSach")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ChiPhiNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DoanhThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TonCuoi")
                        .HasColumnType("int");

                    b.Property<int>("TonDau")
                        .HasColumnType("int");

                    b.Property<int>("TongNhap")
                        .HasColumnType("int");

                    b.Property<int>("TongXuat")
                        .HasColumnType("int");

                    b.HasKey("MaBaoCaoSach", "ISBN");

                    b.HasIndex("ISBN");

                    b.ToTable("CT_BC_Sach");
                });

            modelBuilder.Entity("Bookstore.API.Models.CT_HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDon", "ISBN");

                    b.HasIndex("ISBN");

                    b.ToTable("CT_HoaDon");
                });

            modelBuilder.Entity("Bookstore.API.Models.CT_PhieuNhapSach", b =>
                {
                    b.Property<int>("MaPhieuNhapSach")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuNhapSach", "ISBN");

                    b.HasIndex("ISBN");

                    b.ToTable("CT_PhieuNhapSach");
                });

            modelBuilder.Entity("Bookstore.API.Models.ChucNang", b =>
                {
                    b.Property<int>("MaChucNang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucNang"));

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenManHinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChucNang");

                    b.ToTable("ChucNang");
                });

            modelBuilder.Entity("Bookstore.API.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienTra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Thue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienTamTinh")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("Bookstore.API.Models.HoaDon_UuDai", b =>
                {
                    b.Property<int>("MaCT_HoaDon_UuDai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCT_HoaDon_UuDai"));

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaUuDai")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaCT_HoaDon_UuDai");

                    b.HasIndex("ISBN");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaUuDai");

                    b.ToTable("HoaDon_Uudai");
                });

            modelBuilder.Entity("Bookstore.API.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TienNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TongDonDaMua")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTienDaMua")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaLoaiKhachHang");

                    b.HasIndex("MaSoThue")
                        .IsUnique();

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("Bookstore.API.Models.LoaiKhachHang", b =>
                {
                    b.Property<int>("MaLoaiKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiKhachHang"));

                    b.Property<decimal>("NoToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenLoaiKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TiLeTraToiThieu")
                        .HasColumnType("float");

                    b.HasKey("MaLoaiKhachHang");

                    b.ToTable("LoaiKhachHang");
                });

            modelBuilder.Entity("Bookstore.API.Models.LoaiUuDai", b =>
                {
                    b.Property<int>("MaLoaiUuDai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiUuDai"));

                    b.Property<int>("ApDungToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiUuDai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiUuDai");

                    b.ToTable("LoaiUuDai");
                });

            modelBuilder.Entity("Bookstore.API.Models.NguoiDung", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DangLamViec")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNhomNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayVaoLam")
                        .HasColumnType("date");

                    b.HasKey("TenDangNhap");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaNhomNguoiDung");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("Bookstore.API.Models.NhaCungCap", b =>
                {
                    b.Property<int>("NhaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhaNhaCungCap"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NganHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NhaNhaCungCap");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaSoThue")
                        .IsUnique();

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("Bookstore.API.Models.NhaXuatBan", b =>
                {
                    b.Property<int>("MaNhaXuatBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaXuatBan"));

                    b.Property<string>("TenNhaXuatBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhaXuatBan");

                    b.ToTable("NhaXuatBan");
                });

            modelBuilder.Entity("Bookstore.API.Models.NhomNguoiDung", b =>
                {
                    b.Property<int>("MaNhomNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhomNguoiDung"));

                    b.Property<string>("TenNhomNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhomNguoiDung");

                    b.ToTable("NhomNguoiDung");
                });

            modelBuilder.Entity("Bookstore.API.Models.PhanQuyen", b =>
                {
                    b.Property<int>("MaChucNang")
                        .HasColumnType("int");

                    b.Property<int>("MaNhomNguoiDung")
                        .HasColumnType("int");

                    b.HasKey("MaChucNang", "MaNhomNguoiDung");

                    b.HasIndex("MaNhomNguoiDung");

                    b.ToTable("PhanQuyen");
                });

            modelBuilder.Entity("Bookstore.API.Models.PhienBanSach", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DonGiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaNiemYet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhThucBia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanTaiBan")
                        .HasColumnType("int");

                    b.Property<int>("MaNhaXuatBan")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<int>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<int>("TonKho")
                        .HasColumnType("int");

                    b.Property<int>("TongSoDaBan")
                        .HasColumnType("int");

                    b.HasKey("ISBN");

                    b.HasIndex("MaNhaXuatBan");

                    b.HasIndex("MaSach");

                    b.ToTable("PhienBanSach");
                });

            modelBuilder.Entity("Bookstore.API.Models.PhieuNhapSach", b =>
                {
                    b.Property<int>("MaPhieuNhapSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhapSach"));

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuNhapSach");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("PhieuNhapSach");
                });

            modelBuilder.Entity("Bookstore.API.Models.PhieuThuTien", b =>
                {
                    b.Property<int>("MaPhieuThuTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuThuTien"));

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienThu")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuThuTien");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("PhieuThuTien");
                });

            modelBuilder.Entity("Bookstore.API.Models.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSach"));

                    b.Property<int>("MaTheLoai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSach");

                    b.HasIndex("MaTheLoai");

                    b.ToTable("Sach");
                });

            modelBuilder.Entity("Bookstore.API.Models.TacGia", b =>
                {
                    b.Property<int>("MaTacGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTacGia"));

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTacGia");

                    b.ToTable("TacGia");
                });

            modelBuilder.Entity("Bookstore.API.Models.TacGia_Sach", b =>
                {
                    b.Property<int>("MaTacGia")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.HasKey("MaTacGia", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("TacGia_Sach");
                });

            modelBuilder.Entity("Bookstore.API.Models.ThamSo", b =>
                {
                    b.Property<string>("TenThamSo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GiaTri")
                        .HasColumnType("int");

                    b.HasKey("TenThamSo");

                    b.ToTable("ThamSo");
                });

            modelBuilder.Entity("Bookstore.API.Models.TheLoai", b =>
                {
                    b.Property<int>("MaTheLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTheLoai"));

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTheLoai");

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("Bookstore.API.Models.UuDai", b =>
                {
                    b.Property<int>("MaUuDai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaUuDai"));

                    b.Property<bool>("CoTheSuDung")
                        .HasColumnType("bit");

                    b.Property<int>("MaLoaiKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiUuDai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongDaDung")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenUuDai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaUuDai");

                    b.HasIndex("MaLoaiKhachHang");

                    b.HasIndex("MaLoaiUuDai");

                    b.ToTable("UuDai");
                });

            modelBuilder.Entity("Bookstore.API.Models.UuDai_SachDieuKien", b =>
                {
                    b.Property<int>("MaUuDai")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuongMua")
                        .HasColumnType("int");

                    b.HasKey("MaUuDai", "ISBN");

                    b.HasIndex("ISBN");

                    b.ToTable("UuDai_SachDieuKien");
                });

            modelBuilder.Entity("Bookstore.API.Models.UuDai_SachTang", b =>
                {
                    b.Property<int>("MaUuDai")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuongTang")
                        .HasColumnType("int");

                    b.HasKey("MaUuDai", "ISBN");

                    b.HasIndex("ISBN");

                    b.ToTable("UuDai_SachTang");
                });

            modelBuilder.Entity("Bookstore.API.Models.CTUD_HoaDon_Giam", b =>
                {
                    b.HasOne("Bookstore.API.Models.UuDai", null)
                        .WithMany()
                        .HasForeignKey("MaUuDai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.CTUD_HoaDon_Qua", b =>
                {
                    b.HasOne("Bookstore.API.Models.UuDai", null)
                        .WithMany()
                        .HasForeignKey("MaUuDai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.CTUD_Sach_Giam", b =>
                {
                    b.HasOne("Bookstore.API.Models.UuDai", null)
                        .WithMany()
                        .HasForeignKey("MaUuDai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.CTUD_Sach_Qua", b =>
                {
                    b.HasOne("Bookstore.API.Models.UuDai", null)
                        .WithMany()
                        .HasForeignKey("MaUuDai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.CT_BC_KhachHang", b =>
                {
                    b.HasOne("Bookstore.API.Models.BC_KhachHang", null)
                        .WithMany()
                        .HasForeignKey("MaBaoCaoKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.KhachHang", null)
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.CT_BC_Sach", b =>
                {
                    b.HasOne("Bookstore.API.Models.PhienBanSach", null)
                        .WithMany()
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.BC_Sach", null)
                        .WithMany()
                        .HasForeignKey("MaBaoCaoSach")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.CT_HoaDon", b =>
                {
                    b.HasOne("Bookstore.API.Models.PhienBanSach", null)
                        .WithMany()
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.HoaDon", null)
                        .WithMany()
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.CT_PhieuNhapSach", b =>
                {
                    b.HasOne("Bookstore.API.Models.PhienBanSach", null)
                        .WithMany()
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.PhieuNhapSach", null)
                        .WithMany()
                        .HasForeignKey("MaPhieuNhapSach")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.HoaDon", b =>
                {
                    b.HasOne("Bookstore.API.Models.KhachHang", null)
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.HoaDon_UuDai", b =>
                {
                    b.HasOne("Bookstore.API.Models.PhienBanSach", null)
                        .WithMany()
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.HoaDon", null)
                        .WithMany()
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.UuDai", null)
                        .WithMany()
                        .HasForeignKey("MaUuDai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.KhachHang", b =>
                {
                    b.HasOne("Bookstore.API.Models.LoaiKhachHang", null)
                        .WithMany()
                        .HasForeignKey("MaLoaiKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.NguoiDung", b =>
                {
                    b.HasOne("Bookstore.API.Models.NhomNguoiDung", null)
                        .WithMany()
                        .HasForeignKey("MaNhomNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.PhanQuyen", b =>
                {
                    b.HasOne("Bookstore.API.Models.ChucNang", null)
                        .WithMany()
                        .HasForeignKey("MaChucNang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.NhomNguoiDung", null)
                        .WithMany()
                        .HasForeignKey("MaNhomNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.PhienBanSach", b =>
                {
                    b.HasOne("Bookstore.API.Models.NhaXuatBan", null)
                        .WithMany()
                        .HasForeignKey("MaNhaXuatBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.Sach", null)
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.PhieuNhapSach", b =>
                {
                    b.HasOne("Bookstore.API.Models.NhaCungCap", null)
                        .WithMany()
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.PhieuThuTien", b =>
                {
                    b.HasOne("Bookstore.API.Models.KhachHang", null)
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.Sach", b =>
                {
                    b.HasOne("Bookstore.API.Models.TheLoai", null)
                        .WithMany()
                        .HasForeignKey("MaTheLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.TacGia_Sach", b =>
                {
                    b.HasOne("Bookstore.API.Models.Sach", null)
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.TacGia", null)
                        .WithMany()
                        .HasForeignKey("MaTacGia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.UuDai", b =>
                {
                    b.HasOne("Bookstore.API.Models.LoaiKhachHang", null)
                        .WithMany()
                        .HasForeignKey("MaLoaiKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.LoaiUuDai", null)
                        .WithMany()
                        .HasForeignKey("MaLoaiUuDai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.UuDai_SachDieuKien", b =>
                {
                    b.HasOne("Bookstore.API.Models.PhienBanSach", null)
                        .WithMany()
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.UuDai", null)
                        .WithMany()
                        .HasForeignKey("MaUuDai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.UuDai_SachTang", b =>
                {
                    b.HasOne("Bookstore.API.Models.PhienBanSach", null)
                        .WithMany()
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.UuDai", null)
                        .WithMany()
                        .HasForeignKey("MaUuDai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
