// <auto-generated />
using System;
using Bookstore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookstore.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322100130_AddOTP")]
    partial class AddOTP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bookstore.API.Models.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OTPExpire")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountID = 1,
                            Email = "nathannguyen6002@gmail.com",
                            IsDeleted = false,
                            OTP = "",
                            PasswordHash = "fa980dbf4533c98fa5ed792374bea691610dfaabc62558182f4cc814ef0d69db",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            AccountID = 2,
                            Email = "24521186@gm.uit.edu.vn",
                            IsDeleted = false,
                            OTP = "",
                            PasswordHash = "fa980dbf4533c98fa5ed792374bea691610dfaabc62558182f4cc814ef0d69db",
                            Role = 1,
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("Bookstore.API.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edition")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ImportedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Author = "Aoyama Gosho",
                            CategoryID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Description = "",
                            Edition = 1,
                            ISBN = "978-604-2-27297-1",
                            ImageURL = "",
                            ImportedPrice = 18000m,
                            IsDeleted = false,
                            ListPrice = 25000m,
                            Price = 25000m,
                            Publisher = "NXB Kim Đồng",
                            StockQuantity = 100,
                            Title = "Conan Tập 100"
                        },
                        new
                        {
                            BookID = 2,
                            Author = "Nguyễn Hữu Hùng",
                            CategoryID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 1,
                            Description = "",
                            Edition = 5,
                            ISBN = "978-604-1-18321-4",
                            ImageURL = "",
                            ImportedPrice = 85000m,
                            IsDeleted = false,
                            ListPrice = 120000m,
                            Price = 120000m,
                            Publisher = "NXB Trẻ",
                            StockQuantity = 20,
                            Title = "Lập trình C#"
                        });
                });

            modelBuilder.Entity("Bookstore.API.Models.BookCount", b =>
                {
                    b.Property<int>("BookCountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookCountID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("StockID")
                        .HasColumnType("int");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.HasKey("BookCountID");

                    b.HasIndex("BookID");

                    b.HasIndex("StockID");

                    b.ToTable("BookCounts");
                });

            modelBuilder.Entity("Bookstore.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Truyện tranh"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Giáo trình"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Kỹ năng sống"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Văn học"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Kinh tế"
                        });
                });

            modelBuilder.Entity("Bookstore.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<int?>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPurchaseValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CustomerID");

                    b.HasIndex("AccountID")
                        .IsUnique()
                        .HasFilter("[AccountID] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Address = "Cần Thơ",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Nguyễn Gia Hưng",
                            Email = "",
                            Gender = 0,
                            IsDeleted = false,
                            PhoneNumber = "0901234567",
                            TotalDebt = 0m,
                            TotalOrders = 0,
                            TotalPurchaseValue = 0m
                        });
                });

            modelBuilder.Entity("Bookstore.API.Models.ImportDetail", b =>
                {
                    b.Property<int>("ImportDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportDetailID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("ImportReceiptID")
                        .HasColumnType("int");

                    b.Property<decimal>("ImportedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ImportDetailID");

                    b.HasIndex("BookID");

                    b.HasIndex("ImportReceiptID");

                    b.ToTable("ImportDetails");
                });

            modelBuilder.Entity("Bookstore.API.Models.ImportReceipt", b =>
                {
                    b.Property<int>("ImportReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportReceiptID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewedID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockID")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ImportReceiptID");

                    b.HasIndex("StockID");

                    b.HasIndex("SupplierID");

                    b.ToTable("ImportReceipts");
                });

            modelBuilder.Entity("Bookstore.API.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<decimal>("CustomerPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebtIncurred")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvoiceValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PromotionID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("InvoiceID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("PromotionID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Bookstore.API.Models.InvoiceDetail", b =>
                {
                    b.Property<int>("InvoiceDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceDetailID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("int");

                    b.Property<int>("PromotionID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceDetailID");

                    b.HasIndex("BookID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("PromotionID");

                    b.HasIndex("StockID");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("Bookstore.API.Models.MonthlyDebtReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<decimal>("EndDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncurredDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("CustomerID");

                    b.ToTable("MonthlyDebtReports");
                });

            modelBuilder.Entity("Bookstore.API.Models.MonthlyStockReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("EndCount")
                        .HasColumnType("int");

                    b.Property<int>("ExportedCount")
                        .HasColumnType("int");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("StartCount")
                        .HasColumnType("int");

                    b.Property<int>("StockID")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("BookID");

                    b.HasIndex("StockID");

                    b.ToTable("MonthlyStockReports");
                });

            modelBuilder.Entity("Bookstore.API.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountRate")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GiftBookID")
                        .HasColumnType("int");

                    b.Property<int>("GiftQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LimitUsed")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumOrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PromoType")
                        .HasColumnType("int");

                    b.Property<int>("RequiredBookID")
                        .HasColumnType("int");

                    b.Property<int>("RequiredQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalUsed")
                        .HasColumnType("int");

                    b.HasKey("PromotionID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("GiftBookID");

                    b.HasIndex("RequiredBookID");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Bookstore.API.Models.Receipt", b =>
                {
                    b.Property<int>("ReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<decimal>("ReceiptValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReceiptID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("InvoiceID");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("Bookstore.API.Models.Stock", b =>
                {
                    b.Property<int>("StockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StockID");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            StockID = 1,
                            Description = "Kệ chính, đối diện cửa ra vào",
                            Priority = 0,
                            StockName = "Dãy A"
                        },
                        new
                        {
                            StockID = 2,
                            Description = "Kho tầng 1, lưu trữ hàng mới nhập về",
                            Priority = 1,
                            StockName = "Kho tổng 1"
                        },
                        new
                        {
                            StockID = 3,
                            Description = "Kho tầng 2, lưu trữ hàng tồn kho, chưa xả được",
                            Priority = 1,
                            StockName = "Kho tổng 2"
                        });
                });

            modelBuilder.Entity("Bookstore.API.Models.StockTransfer", b =>
                {
                    b.Property<int>("TransferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("FromStockID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("ToStockID")
                        .HasColumnType("int");

                    b.HasKey("TransferID");

                    b.HasIndex("FromStockID");

                    b.HasIndex("ToStockID");

                    b.ToTable("StockTransfers");
                });

            modelBuilder.Entity("Bookstore.API.Models.StockTransferDetail", b =>
                {
                    b.Property<int>("StockTransferDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockTransferDetailID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TransferID")
                        .HasColumnType("int");

                    b.HasKey("StockTransferDetailID");

                    b.HasIndex("BookID");

                    b.HasIndex("TransferID");

                    b.ToTable("StockTransferDetails");
                });

            modelBuilder.Entity("Bookstore.API.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierID = 1,
                            Address = "55 Quang Trung, Hà Nội",
                            Email = "cskh@nxbkimdong.com.vn",
                            Phonenumber = "1900571595",
                            SupplierName = "NXB Kim Đồng"
                        },
                        new
                        {
                            SupplierID = 2,
                            Address = "161B Lý Chính Thắng, Quận 3, TP.HCM",
                            Email = "hopthu@nxbtre.com.vn",
                            Phonenumber = "02839316289",
                            SupplierName = "NXB Trẻ"
                        });
                });

            modelBuilder.Entity("Bookstore.API.Models.Book", b =>
                {
                    b.HasOne("Bookstore.API.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.BookCount", b =>
                {
                    b.HasOne("Bookstore.API.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.Stock", null)
                        .WithMany()
                        .HasForeignKey("StockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.Customer", b =>
                {
                    b.HasOne("Bookstore.API.Models.Account", null)
                        .WithOne()
                        .HasForeignKey("Bookstore.API.Models.Customer", "AccountID");
                });

            modelBuilder.Entity("Bookstore.API.Models.ImportDetail", b =>
                {
                    b.HasOne("Bookstore.API.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.ImportReceipt", null)
                        .WithMany()
                        .HasForeignKey("ImportReceiptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.ImportReceipt", b =>
                {
                    b.HasOne("Bookstore.API.Models.Stock", null)
                        .WithMany()
                        .HasForeignKey("StockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.Invoice", b =>
                {
                    b.HasOne("Bookstore.API.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.HasOne("Bookstore.API.Models.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionID");
                });

            modelBuilder.Entity("Bookstore.API.Models.InvoiceDetail", b =>
                {
                    b.HasOne("Bookstore.API.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionID");

                    b.HasOne("Bookstore.API.Models.Stock", null)
                        .WithMany()
                        .HasForeignKey("StockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.MonthlyDebtReport", b =>
                {
                    b.HasOne("Bookstore.API.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.MonthlyStockReport", b =>
                {
                    b.HasOne("Bookstore.API.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.Stock", null)
                        .WithMany()
                        .HasForeignKey("StockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.Promotion", b =>
                {
                    b.HasOne("Bookstore.API.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("GiftBookID");

                    b.HasOne("Bookstore.API.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("RequiredBookID");
                });

            modelBuilder.Entity("Bookstore.API.Models.Receipt", b =>
                {
                    b.HasOne("Bookstore.API.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.HasOne("Bookstore.API.Models.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceID");
                });

            modelBuilder.Entity("Bookstore.API.Models.StockTransfer", b =>
                {
                    b.HasOne("Bookstore.API.Models.Stock", null)
                        .WithMany()
                        .HasForeignKey("FromStockID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.Stock", null)
                        .WithMany()
                        .HasForeignKey("ToStockID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookstore.API.Models.StockTransferDetail", b =>
                {
                    b.HasOne("Bookstore.API.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.API.Models.StockTransfer", null)
                        .WithMany()
                        .HasForeignKey("TransferID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
