<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Icons\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\book1.png" />
    <None Remove="Resources\Images\book2.png" />
    <None Remove="Resources\Images\book3.png" />
    <None Remove="Resources\Images\book4.png" />
    <None Remove="Resources\Images\book5.png" />
    <None Remove="Resources\Images\Books\300baicode.jpg" />
    <None Remove="Resources\Images\Books\canhdongbattan.jpg" />
    <None Remove="Resources\Images\Books\caphecungtony.jpg" />
    <None Remove="Resources\Images\Books\chipheo.jpg" />
    <None Remove="Resources\Images\Books\cleancode.jpg" />
    <None Remove="Resources\Images\Books\cleancoder.jpg" />
    <None Remove="Resources\Images\Books\conan1.jpg" />
    <None Remove="Resources\Images\Books\conan2.jpg" />
    <None Remove="Resources\Images\Books\dacnhantam.jpg" />
    <None Remove="Resources\Images\Books\designpatterns.jpg" />
    <None Remove="Resources\Images\Books\doraemon1.jpg" />
    <None Remove="Resources\Images\Books\doraemon2.jpg" />
    <None Remove="Resources\Images\Books\gian.jpg" />
    <None Remove="Resources\Images\Books\harrypotter1.jpg" />
    <None Remove="Resources\Images\Books\harrypotter2.jpg" />
    <None Remove="Resources\Images\Books\kafka.jpg" />
    <None Remove="Resources\Images\Books\matbiec.jpg" />
    <None Remove="Resources\Images\Books\nhagiakim.jpg" />
    <None Remove="Resources\Images\Books\quangganhlo.jpg" />
    <None Remove="Resources\Images\Books\refactoring.jpg" />
    <None Remove="Resources\Images\Books\rungnauy.jpg" />
    <None Remove="Resources\Images\Books\sodo.jpg" />
    <None Remove="Resources\Images\Books\thienac.jpeg" />
    <None Remove="Resources\Images\Books\trenduongbang.jpg" />
    <None Remove="Resources\Images\Books\vetuoitho.jpg" />
    <None Remove="Resources\Images\Login\bg0.png" />
    <None Remove="Resources\Images\Login\bg1_1.png" />
    <None Remove="Resources\Images\Login\bg1_2.png" />
    <None Remove="Resources\Images\Login\bg1_3.png" />
    <None Remove="Resources\Images\Login\bg1_4.png" />
    <None Remove="Resources\Images\Login\bg1_5.png" />
    <None Remove="Resources\Images\Login\login0.png" />
    <None Remove="Resources\Images\Login\login1.png" />
    <None Remove="Resources\Images\Login\login2.png" />
    <None Remove="Resources\Images\your_avatar.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Icons\AppIcon.ico" />
    <Content Include="Resources\Images\book1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\book2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\book3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\book4.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\book5.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Resources\Images\Books\300baicode.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\canhdongbattan.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\caphecungtony.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\chipheo.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\cleancode.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\cleancoder.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\conan1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\conan2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\dacnhantam.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\default_book_cover.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\designpatterns.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\doraemon1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\doraemon2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\gian.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\harrypotter1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\harrypotter2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\kafka.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\matbiec.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\nhagiakim.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\quangganhlo.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\refactoring.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\rungnauy.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\sodo.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\thienac.jpeg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\trenduongbang.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Books\vetuoitho.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\your_avatar.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="EPPlus" Version="8.5.4" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.1-ci1292" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView" Version="2.1.0-dev-247" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.1.0-dev-247" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
    <PackageReference Include="NuGet.Packaging" Version="6.11.2" />
    <PackageReference Include="NuGet.Protocol" Version="6.11.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bookstore.Share\Bookstore.Share.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\Login\Background.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Login\bg0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Login\bg1_1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Login\bg1_2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Login\bg1_3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Login\bg1_4.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Login\bg1_5.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Login\login0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Login\login1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Login\login2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
